# Generated by Django 4.1 on 2022-08-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('mobile_code', models.CharField(max_length=3)),
                ('tag', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MailSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_start', models.DateTimeField()),
                ('pub_end', models.DateTimeField()),
                ('text', models.TextField(max_length=512)),
                ('mobile_code', models.CharField(max_length=3)),
                ('client_tag', models.CharField(max_length=100)),
            ],
        ),
    ]
