# Generated by Django 4.1 on 2022-08-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsend',
            name='pub_end',
            field=models.DateTimeField(verbose_name='Дата и время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailsend',
            name='pub_start',
            field=models.DateTimeField(verbose_name='Дата и время запуска рассылки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('S', 'Sent'), ('F', 'Failed'), ('D', 'Delivered'), ('U', 'Undelivered'), ('N', 'Not sent')], default='N', editable=False, max_length=10),
        ),
    ]
