# Generated by Django 4.1 on 2022-08-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mailsend_pub_end_alter_mailsend_pub_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата и время отправки сообщения'),
        ),
    ]
